pull_request_rules:
  - name: automatic merge when CI passes and all requested reviewers approved
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - status-success=nGraph-ONNX Jenkins CI (IGK)
      - base=master
      - label!=WIP
    actions:
      merge:
        method: squash
        strict: true

  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
