sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t test_ngraph_onnx -f .ci/travis/ubuntu/Dockerfile .

install: true

script:
  - docker run test_ngraph_onnx

branches:
  only:
    - "master"
